apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-superb-yeti
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "712906141828"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: lfs268-411509
    provider: gke
    registry: gcr.io
    zone: europe-west1-b
  environments:
  - key: dev
    owner: AlbertGoma-LFS268-CICD-JenkinsX
    repository: cluster
  - key: staging
  - key: production
  ingress:
    domain: 34.76.221.114.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: LFS268bot
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-superb-yeti-74df5df25626
  - name: reports
    url: gs://reports-tf-jx-superb-yeti-74df5df25626
  - name: repository
    url: gs://repository-tf-jx-superb-yeti-74df5df25626
  vault: {}
  webhook: lighthouse
